### PR TITLE
Update dependencies & add Snyk

### LINKED ISSUE #48: USWDS-Compile - Bug: gulp vulnerability
# Special Note
In digging into this deeper, this appears to be an issue with Gulp, instead of this repo as uswds is on the latest version of gulp and all of the dependency issues reside with gulp 4.0.2. Uswds will need to be upgraded once Gulp fixes its issues

### Describe the bug

The issue I am seeing is that USWDS-Compile relies on a version of Gulp that has a transitive dependency with a valid vulnerability:

https://security.snyk.io/package/npm/glob-parent

```
# npm audit report

glob-parent  <5.1.2
Severity: high
glob-parent before 5.1.2 vulnerable to Regular Expression Denial of Service in enclosure regex - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix --force`
Will install undefined@undefined, which is a breaking change
node_modules/chokidar/node_modules/glob-parent
node_modules/glob-stream/node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/chokidar
    glob-watcher  >=3.0.0
    Depends on vulnerable versions of chokidar
    node_modules/glob-watcher
      gulp  >=4.0.0
      Depends on vulnerable versions of glob-watcher
      node_modules/gulp
        @uswds/compile  *
        Depends on vulnerable versions of gulp
        node_modules/@uswds/compile
  glob-stream  5.3.0 - 6.1.0
  Depends on vulnerable versions of glob-parent
  node_modules/glob-stream
    vinyl-fs  >=2.4.2
    Depends on vulnerable versions of glob-stream
    node_modules/vinyl-fs

7 high severity vulnerabilities
```

```
~\web>npm ls glob-parent
~\web
+-- @uswds/compile@1.0.0-beta.3
| `-- gulp@4.0.2
|   +-- glob-watcher@5.0.5
|   | `-- chokidar@2.1.8
|   |   `-- glob-parent@3.1.0
|   `-- vinyl-fs@3.0.3
|     `-- glob-stream@6.1.0
|       `-- glob-parent@3.1.0
```

this version of gulp also has a transitive dependency vulnerability for yargs-parser:
```
+-- @uswds/compile@1.0.0-beta.3
| +-- gulp-replace@1.1.3
| | `-- yargs-parser@21.1.1
| `-- gulp@4.0.2
|   `-- gulp-cli@2.3.0
|     `-- yargs@7.1.2
|       `-- yargs-parser@5.0.1

```

### Steps to reproduce the bug

run npm install uswds-compile
run npm audit

### Expected Behavior

there should be no errors, would it be possible to upgrade the gulp dependency to a version that is not affected by this?

### Related code

_No response_

### Screenshots

_No response_

### System setup

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-compile/issues) for duplicate bug reports.

### PR DESCRIPTION
**Pull request by mejiaj**
This PR:
- Security fixes via `overrides`
- Updates dependencies
- Adds Snyk monitor via CLI

Closes #48.

## Dependency updates

| Dependency                     |     Old | 25da089 [04/27/23] | b37aee6 [07/12/23] |
| :----------------------------- | ------: | -----------------: | -----------------: |
| `@uswds/uswds`                 |   3.3.0 |              3.4.1 |              3.5.0 |
| `uswds`                        |  2.13.3 |             2.14.0 |                  - |
| `autoprefixer`                 | 10.4.13 |            10.4.14 |                  - |
| `del`                          |   6.0.0 |              6.1.1 |                  - |
| `glob-parent`  [⚠️ via overrides] |       - |              6.0.2 |                  - |
| `gulp-replace`                 |   1.1.3 |              1.1.4 |                  - |
| `postcss`                      |  8.4.19 |             8.4.23 |             8.4.25 |
| `sass-embedded`                |  1.56.1 |             1.62.0 |             1.63.6 |
| `unset-value` [⚠️ via overrides]  |       - |              2.0.1 |                  - |

> **Note**
> There is an additional update for `del@7`, but that **only** supports ESM.

## How to test

<details><summary>Confirm errors</summary>
<p></p>

1. Checkout `git checkout develop` branch
1. Run `npm i && npm audit`
1. Confirm error message: `6 high severity vulnerabilities`
1. Run `npx snyk test`
1. Confirm error message: `found 2 issues, 33 vulnerable paths.`
1. Reset branch with `git checkout -- .`

</details> 
 
<details><summary>Confirm fix</summary>

<p></p>

1. Checkout branch `git checkout  jm-update-dependencies`
1. Run `npm i && npm audit`
1. Confirm 0 vulnerabilities
1. Run snyk test `npx snyk test`
1. Confirm 0 vulnerabilities.

> **Note**
> I tried testing this on uswds-sandbox with mixed results. Installing via 
>npm link will show dependency fixes, but gulp scripts won't run (even if Node versions match). Installing via git branch won't show security fixes, but scripts **will** run.
</details>  

Test functionality:

- All gulp tasks should run without errors. Test branch available in Sandbox [branch `test-compile-60`](https://github.com/uswds/uswds-sandbox/tree/test-compile-60) or use site.
- There should be zero vulnerabilities in `npm audit`.

### CODE REVIEW

**Review by mahoneycm — COMMENTED** [review]
When running `npx snyk test` I'm receiving a third failure on `develop` that persists on this branch.

image

I'm also receiving an error during `buildSass` on the following fulp tasks
- `compile`
- `compileSass`
- `updateUswds` _// runs `compile` mentioned above_

`Error: Cannot find module '../../uswds/package.json'`

image


If I update the path to package.json I'm able to resolve it

```diff
-  const pkg = require(`../../${uswdsPath}/package.json`).version;
+  const pkg = require(`../${uswdsPath}/package.json`).version; 
```

Curious why I've received this error if you haven't!

**Review by amyleadem — COMMENTED** [review]
@mejiaj This is looking good, but I had trouble removing the vulnerabilities when I installed this branch on `uswds-site`.  It looks like you ran into a similar issue as described in your PR description. I am not sure if that is an issue with the install method or with the overrides themselves, just wanted to flag it.

- [x] Successfully completed all steps to confirm vulnerabilities in `develop`
- [x] Successfully completed all steps to confirm 0 vulnerabilities in this branch
- [x] Confirmed that all gulp tasks work on a local uswds and uswds-compile project
- [x] Confirmed dependencies are now on their latest  version (with the exception of `del`)
- [x] Confirmed dependency table in the PR description matches updated dependencies
- [ ] Confirmed this branch removes `unset-value` and `glob-parent` snyk errors in uswds-site
    - When I install the `jm-update-dependencies` branch in uswds-site, via both `npm link` and installing the remote branch, it shows `6 high severity vulnerabilities` and does not resolve `glob-parent` or `unset-value` snyk errors. I confirmed that @uswds/compile had the overrides in its `package.json`.

**Comment by mejiaj** [comment]
@mahoneycm 

> When running `npx snyk test` I'm receiving a third failure on `develop` that persists on this branch.
> 
> image

This is after removing `node_modules` and `package-lock.json`?

<details><summary>How I tested</summary>
<p></p>

```bash
uswds-compile on  jm-update-dependencies via  v18.15.0 via 💎 v2.7.2 
➜ rm -rf node_modules package-lock.json             
npm %                                                                                                                                                                     

uswds-compile on  jm-update-dependencies [✘] via  v18.15.0 via 💎 v2.7.2 
➜ npm i                                             
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies

added 512 packages, and audited 513 packages in 13s

45 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

uswds-compile on  jm-update-dependencies [!1] via  v18.15.0 via 💎 v2.7.2 took 13s 
➜ npx snyk test                                     

Testing /Users/jmejia-a/web/uswds-compile...

Organization:      uswds
Package manager:   npm
Target file:       package-lock.json
Project name:      @uswds/compile
Open source:       no
Project path:      /Users/jmejia-a/web/uswds-compile
Licenses:          enabled

✔ Tested 415 dependencies for known issues, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.
```
</details> 

---

> I'm also receiving an error during `buildSass` on the following fulp tasks
> 
> * `compile`
> * `compileSass`
> * `updateUswds` _// runs `compile` mentioned above_
> 
> `Error: Cannot find module '../../uswds/package.json'`
> 
> image
> 
> If I update the path to package.json I'm able to resolve it
> 
> ```diff
> -  const pkg = require(`../../${uswdsPath}/package.json`).version;
> +  const pkg = require(`../${uswdsPath}/package.json`).version; 
> ```
> 
> Curious why I've received this error if you haven't!

You need a test project to run the Compile tasks. I've updated notes to point to [uswds/uswds-sandbox at test-compile-60](https://github.com/uswds/uswds-sandbox/tree/test-compile-60).

**Comment by mejiaj** [comment]
> @mejiaj This is looking good, but I had trouble removing the vulnerabilities when I installed this branch on `uswds-site` (notes below). It looks like you ran into a similar issue as described in your PR description. I am not sure if that is an issue with the install method or with the overrides themselves, just wanted to flag it.
> 
> * [x]  Successfully completed all steps to confirm vulnerabilities in `develop`
> * [x]  Successfully completed all steps to confirm 0 vulnerabilities and no snyk errors in this branch
> * [x]  Confirmed that all gulp tasks work when installed on a local uswds and uswds-compile project
> * [x]  Confirmed dependencies are now on their latest  version (with the exception of `del`)
> * [x]  Confirmed dependency table in the PR description matches updated dependencies
> * [ ]  Confirmed this branch removes `unset-value` and `glob-parent` snyk errors in uswds-site
>   
>   * When I install the `jm-update-dependencies` branch in uswds-site, via both `npm link` and installing the remote branch, it shows `6 high severity vulnerabilities` and does not resolve `glob-parent` or `unset-value` snyk errors. I confirmed that @uswds/compile had the overrides in its `package.json`.

I focused on this repo when testing vulnerabilities. I was able to reproduce the last note and not sure why that's happening. It might be an issue with `npm audit`, but the main focus was handling the issues in this repo.

**Review by amyleadem — APPROVED** [review]
Looks good to me!

**Review by mahoneycm — COMMENTED** [review]
@mejiaj I was able to run the gulp commands on the test repo linked in the description but I still received the `npx snyk test` failure after removing `node_modules` and `package-lock.json`


<details> 

<summary>Terminal results</summary>

```bash
uswds-compile on  jm-update-dependencies [!] is 📦 v1.0.0 via  v16.19.0 via 💎 v2.6.10 
❯ rm -rf node_modules package-lock.json

uswds-compile on  jm-update-dependencies [✘!] is 📦 v1.0.0 via  v16.19.0 via 💎 v2.6.10 
❯ npm i        
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies

added 513 packages, and audited 514 packages in 23s

46 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

uswds-compile on  jm-update-dependencies [!] is 📦 v1.0.0 via  v16.19.0 via 💎 v2.6.10 took 23s 
❯ npx snyk test

Testing /Users/cmahoney/web/uswds-compile...

Tested 420 dependencies for known issues, found 1 issue, 5 vulnerable paths.


Issues with no direct upgrade or patch:
  ✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://security.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908] in ansi-regex@2.1.1
    introduced by gulp@4.0.2 > gulp-cli@2.3.0 > yargs@7.1.2 > string-width@1.0.2 > strip-ansi@3.0.1 > ansi-regex@2.1.1 and 4 other path(s)
  This issue was fixed in versions: 3.0.1, 4.1.1, 5.0.1, 6.0.1



Organization:      mahoneycm-gsa
Package manager:   npm
Target file:       package-lock.json
Project name:      @uswds/compile
Open source:       no
Project path:      /Users/cmahoney/web/uswds-compile
Licenses:          enabled
```

</details>

**Comment by mejiaj** [comment]
@mahoneycm can you do a clean install and test again?

**Comment by mahoneycm** [comment]
@mejiaj same issue as before:

image

**Comment by mejiaj** [comment]
I've updated dependencies and run `npm audit fix` in [b37aee6](https://github.com/uswds/uswds-compile/pull/60/commits/b37aee6057c08543a1e0f51b1277da757c81d587).

And now we're back to zero vulnerabilities.

```bash
# 07/12/23 - After `npm audit fix`.
uswds-compile on jm-update-dependencies [+] via NPM v18.15.0 
→ npm audit fix

changed 2 packages, and audited 513 packages in 478ms

39 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by mejiaj** [comment]
As of 09/07/23 there are still 0 vulnerabilities. This is ready for review & merge.

**Comment by jeremyzilar** [comment]
On a fresh install where `@uswds/compile` is the only dependency, I am finding that it hangs on `caniuse-lite`. Then after about 15mins, my computer runs out of memory and crashes. I am on node `16.19.1`.
image

**Comment by jeremyzilar** [comment]
FWIW -- I downgraded to node `14.21.3` and got it working, _I think_ 😊

**Comment by mejiaj** [comment]
@jeremyzilar could you try node 20? That's the latest LTS version.

**Pull request merged**
