### PR TITLE
USWDS-Compile - Gulp: Support disabling sass sourcemaps

### LINKED ISSUE #70: USWDS-Compile - Feature: Allow disabling sourcemaps
### Is your feature request related to a problem? Please describe.

When using this tool in our USWDS + Drupal + static site generation setup the .map sourcemap files aren't copied over because they are comments in the css and not actual source file references. This causes the .map files to be listed as missing in the console. If we can conditionally disable sourcemaps as an option then we would not have missing files in the console log.

### Describe the solution you'd like

Add an option to disable sourcemaps in the output css.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-compile/issues) for duplicate feature requests.

### PR DESCRIPTION
**Pull request by mdmower-csnw**
- Drop `gulp-sourcemaps` which is seemingly neglected and is the reason for 3 npm audit warnings. Gulp v4 and v5 have native support for toggling sourcemaps.
- Add new boolean setting `settings.compile.sassSourcemaps` that defaults to `true` but can be set to `false` in consumer projects to disable outputting sass sourcemaps.

This addresses the sass portion of #70. Exclusion of USWDS JS sourcemaps would need a separate setting and handling.

## Related issue
Closes #70

### CODE REVIEW

**Review by mejiaj — APPROVED** [review]
Thanks for submitting this PR!

Verified setting works as expected. Created a test PR in uswds/uswds-sandbox#143.

| Before | After |
| :----- | :---- |
| image | image | 

## Dependencies

**Before** [develop]
```node
14 vulnerabilities (3 moderate, 11 high)
```

**After**
Moderate vulnerabilities are gone.
```node
11 high severity vulnerabilities
```

**Review by mahoneycm — APPROVED** [review]
Working like a charm! Thanks for your contribution

- [x] No perceived regressions or build errors when installed on site
- [x] Sourcemaps included by default
- [x] Successfully disabled sourcemaps via `settings.compile.sassSourcemaps`

**Comment by mdmower-csnw** [comment]
@mahoneycm @mejiaj - Would you like me to resolve the merge conflicts since #96 was merged, or would you like to handle that?

**Comment by mejiaj** [comment]
@mdmower-csnw if you're able to resolve with the latest that would help a lot!

**Comment by mdmower-csnw** [comment]
@mejiaj - When I attempted to test these changes with the current `develop` branch, I ran into a new issue: #110 . It would be best if that issue is cleaned up in `develop` before I resolve conflicts in this PR. Let me know if you need any more information there.

**Comment by mdmower-csnw** [comment]
@mejiaj - I retested this PR after merging the latest from `develop` along with #110 to make sure there aren't any regressions with Gulp v5. Things look good from my end.

For a project where I use uswds 3.7.1...
- the generated sourcemap `styles.css.map` is identical when using Gulp v5 built-in sourcemaps (this PR) compared to using package `gulp-sourcemaps` (without this PR).
- disabling sass-sourcemaps still works with setting `settings.compile.sassSourcemaps`.

I've gone ahead and merged upstream `develop` into this branch because there are no merge conflicts introduced with #110 (this PR and that PR can be merged in any order).

**Review by heymatthenry — APPROVED** [review]

**Pull request merged**
