### PR TITLE
Allow functions to work within a containerized environment by switching sass-embedded to sass

### PR DESCRIPTION
**Pull request by smustgrave**
https://github.com/uswds/uswds-compile/issues/20

### CODE REVIEW

**Comment by mejiaj** [comment]
@smustgrave so removing sass embedded didn't fix the issue?

@thisisdano should we close this issue or re-frame it so there's an option to switch from sass to sass-embedded?

**Comment by smustgrave** [comment]
@mejiaj removing sass-embedded did fix the issue for us.  Haven't had a change to break apart the node module to figure out why that one is failing.

**Review by mejiaj — CHANGES_REQUESTED** [review]
@smustgrave thanks for the contribution. Ideally users should be able to choose between embedded vs sass. We don't want to lose the performance benefits of embedded to users who _can_ use it.

This would be a boolean that would, ideally, conditionally load sass with and without sass embedded.

**Comment by mejiaj** [comment]
Closing in favor of solution for #32.

**Pull request closed without merging**
