### PR TITLE
USWDS-Compile - POAM: August '24

### PR DESCRIPTION
**Pull request by mahoneycm**
# Summary

POAM dependency updates for August 2024.

## Vulnerabilities

No changes in vulnerabilities

```node
found 0 vulnerabilities
```

## Testing instructions

1. Install this branch on site
    - On Site's `main` branch, run: 
  ```bash
npm install "https://github.com/uswds/uswds-compile/tree/cm-POAM-august-2024" --save
```
2. Run gulp sass scripts and ensure compile runs as expected without error.
3. Ensure no regressions when package is used to compile site

## Dependency updates

| Dependency name | Previous version | Updated version |
|--------|--------|--------|
| autoprefixer | 10.4.19  | 10.4.20 | 
| postcss | ^8.4.39  | ^8.4.40 | 
| sass-embedded | 1.77.5 | 1.77.8 |

### CODE REVIEW

**Review by mejiaj — APPROVED** [review]
No issues found, but noting that after installing and running in Sandbox I'm seeing the SASS deprecation warnings in uswds/uswds#5980.

Install feature branch in sandbox.

```sh
npm i "uswds/uswds-compile#cm-POAM-august-2024"
```

Run build SASS task.

```sh
uswds-sandbox on  main [$!2] via  v20.16.0 via 💎 v2.7.2
❯ npx gulp buildSass
[11:13:45] Using gulpfile ~/web/uswds-sandbox/gulpfile.js
[11:13:45] Starting 'buildSass'...
[11:13:45] Starting 'logVersion'...
uswds.version: 3
[11:13:45] Finished 'logVersion' after 498 μs
[11:13:45] Starting 'buildSass'...
Compiling with USWDS 3.8.1
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ┌──> ../../../@uswds/uswds/packages/uswds-core/src/styles/mixins/utilities/_font.scss
42 │     font-family: ff($family);
   │     ^^^^^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> ../../../@uswds/uswds/packages/uswds-core/src/styles/mixins/typography/typeset.scss
50 │ ┌   + * {
51 │ │     margin-top: $theme-paragraph-margin-top;
52 │ │   }
   │ └─── nested rule
   ╵
    ../../../@uswds/uswds/packages/uswds-core/src/styles/mixins/utilities/_font.scss 42:3      u-font()
    ../../../@uswds/uswds/packages/uswds-core/src/styles/mixins/typography/typeset.scss 34:3   typeset()
    ../../../@uswds/uswds/packages/uswds-core/src/styles/mixins/typography/headings.scss 27:3  h3()
    ../../../@uswds/uswds/packages/uswds-core/src/styles/mixins/typography/headings.scss 64:3  typeset-h3()
    ../../../@uswds/uswds/packages/usa-display/src/styles/_usa-display.scss 4:3                @forward
    ../../../@uswds/uswds/packages/usa-display/src/styles/_index.scss 4:1                      @forward
    _index.scss 5:1                                                                            @forward
    _index.scss 5:1                                                                            @forward
    _index.scss 13:1                                                                           @forward
    ../../../../src/_styles/styles.scss 2:1                                                    root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.
```

**Review by amyleadem — APPROVED** [review]
Looks good to me. 

I tested locally in both `uswds-site` using USWDS v3 and in `uswds-sandbox` using USWDS v2 (using PR https://github.com/uswds/uswds-sandbox/pull/147 as a base).

Confirming that I now see the same Sass deprecation warnings that @mejiaj noted in his comment. 

> [!Note] 
> I took the liberty of updating the dependency table in the PR description to include some missing dependency updates. Please confirm that the info in the dependency table matches the updates in package.json.

**Comment by amyleadem** [comment]
Noting that I also tagged this PR for release 1.2.0. Please remove this milestone if this PR does not belong in 1.2.0.

**Review by thisisdano — APPROVED** [review]
I see the deprecation warnings. We'll get this updated in the uswds codebase asap, but that shouldn't block this merge and this 1.2.0 release!

**Pull request merged**
